"""Exact computations for permutations and birdtrack operators."""

from typing import Any

from .linear_combinations import (
    CoefficientPrecisionWarning,
    DimensionPolynomial,
    PermutationSum,
    PolynomialPermutationSum,
    configure_coefficient_safety,
    multiply_sums,
)
from .permutations import (
    Permutation,
    compose,
    cycle_notation,
    get_display_notation,
    latex,
    multiply_many,
    set_display_notation,
)
from .symbolic import Polynomial, SymbolicCoefficient, parse_symbolic
from .projectors import (
    AlgebraicIdentity,
    ANTISYMMETRISER_RECURSION,
    Antisymmetriser,
    DiagramAlgebraBackend,
    DiagramValueCodec,
    DefinitionKind,
    DefinitionLine,
    Connection,
    IDENTITIES,
    DetangleAction,
    DetangleMetrics,
    DetangleSearchResult,
    DetangleState,
    ExposureTarget,
    LearnedDetangler,
    LearnedDetangleResult,
    MULTIPLY_CONNECTED_S_A_ANNIHILATION,
    SAME_TYPE_NESTED_ABSORPTION,
    NodePort,
    Projector,
    ProjectorAlgebraBackend,
    ProjectorCanvasSession,
    ProjectorConfiguration,
    ProjectorNode,
    ProjectorSum,
    ProjectorValueCodec,
    PermutationNode,
    Symmetriser,
    SATarget,
    StrandPath,
    TypedWhiteboardSidecar,
    ValueCodec,
    WhiteboardSidecar,
    WhiteboardStores,
    collapse_resolved_sa_pair,
    create,
    diagram_backend,
    diagram_codec,
    projector_codec,
    projector_backend,
    resolve_sidecar_path,
    to_latex,
    whiteboard_latex,
    write_sidecar,
    write_typed_sidecar,
    whiteboard,
    SYMMETRISER_RECURSION,
    beam_search_detangle,
    detangle_game,
    expand_node,
    permute_node_ports,
    recursive_expand_node,
    greedy_detangle,
    load_detangle_demonstrations,
    load,
    expose_sa_target_step,
    exposure_training_game,
    find_sa_exposure_targets,
    find_sa_targets,
    hybrid_collapse,
    hybrid_reduce,
    hybrid_dataset_overview,
    hybrid_simplify_step,
    load_exposure_problems,
    load_resolver_problems,
    random_exposure_problem,
    random_resolver_problem,
    remove_multiply_connected_s_a_terms,
    simplify_step,
    resolve_sa_target_step,
    sa_pair_paths,
    sa_pair_ready_to_collapse,
    resolver_training_game,
)

__all__ = [
    "Pair",
    "AlgebraicIdentity",
    "ANTISYMMETRISER_RECURSION",
    "Antisymmetriser",
    "DiagramAlgebraBackend",
    "DiagramValueCodec",
    "DefinitionKind",
    "DefinitionLine",
    "CoefficientPrecisionWarning",
    "Connection",
    "DimensionPolynomial",
    "IDENTITIES",
    "DetangleAction",
    "DetangleMetrics",
    "DetangleSearchResult",
    "DetangleState",
    "ExposureTarget",
    "LearnedDetangler",
    "LearnedDetangleResult",
    "MULTIPLY_CONNECTED_S_A_ANNIHILATION",
    "SAME_TYPE_NESTED_ABSORPTION",
    "NodePort",
    "Permutation",
    "PermutationSum",
    "PolynomialPermutationSum",
    "Polynomial",
    "SymbolicCoefficient",
    "parse_symbolic",
    "Projector",
    "ProjectorAlgebraBackend",
    "ProjectorCanvasSession",
    "ProjectorConfiguration",
    "ProjectorNode",
    "ProjectorSum",
    "ProjectorValueCodec",
    "PermutationNode",
    "Symmetriser",
    "SATarget",
    "StrandPath",
    "ValueCodec",
    "WhiteboardSidecar",
    "WhiteboardStores",
    "TypedWhiteboardSidecar",
    "diagram_backend",
    "diagram_codec",
    "collapse_resolved_sa_pair",
    "create",
    "whiteboard",
    "to_latex",
    "whiteboard_latex",
    "projector_codec",
    "projector_backend",
    "resolve_sidecar_path",
    "write_sidecar",
    "write_typed_sidecar",
    "SYMMETRISER_RECURSION",
    "beam_search_detangle",
    "compose",
    "configure_coefficient_safety",
    "cycle_notation",
    "get_display_notation",
    "latex",
    "multiply_many",
    "multiply_sums",
    "set_display_notation",
    "expand_node",
    "permute_node_ports",
    "recursive_expand_node",
    "detangle_game",
    "greedy_detangle",
    "load_detangle_demonstrations",
    "load",
    "expose_sa_target_step",
    "exposure_training_game",
    "find_sa_exposure_targets",
    "find_sa_targets",
    "hybrid_dataset_overview",
    "hybrid_collapse",
    "hybrid_reduce",
    "hybrid_simplify_step",
    "load_exposure_problems",
    "load_resolver_problems",
    "random_exposure_problem",
    "random_resolver_problem",
    "remove_multiply_connected_s_a_terms",
    "simplify_step",
    "resolve_sa_target_step",
    "sa_pair_paths",
    "sa_pair_ready_to_collapse",
    "resolver_training_game",
]


def __getattr__(name: str) -> Any:
    """Load optional representation classes only when requested."""
    if name == "Pair":
        from .representations import pair_backend

        return pair_backend().Pair
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | {"Pair"})
